### PR TITLE
Closes #77 Listen command throws error

### LINKED ISSUE #77: Listen command throws error
### Lemon Squeezy for Laravel Version

1.5.0

### Laravel Version

10.x

### PHP Version

8.3

### Description

There's an issue with the listen command and a signing secret. For some reason it's throwing an error on a first run on a fresh install. Need to investigate this... would love some insights from anyone if able to.

### Steps To Reproduce

https://youtu.be/Zx6VhRzOMkQ?t=486

### PR DESCRIPTION
**Pull request by DanielHudson**
Handles when `LEMON_SQUEEZY_SIGNING_SECRET` is not set in the env, by falling back to a hash of the `LEMON_SQUEEZY_API_KEY`

### CODE REVIEW

File: src/Console/ListenCommand.php [hunk 1]
```diff
@@ -269,7 +266,7 @@ protected function setupWebhook(string $tunnel): void
                         'license_key_created',
                         'license_key_updated',
                     ],
-                    'secret' => config('lemon-squeezy.signing_secret'),
+                    'secret' => config('lemon-squeezy.signing_secret') ?: Str::limit(Hash::make(config('lemon-squeezy.api_key')), 32, '')
```
Comment (driesvints) [inline src/Console/ListenCommand.php:269]: Wondering if this isn't just simpler? 🤔 

```suggestion
                    'secret' => config('lemon-squeezy.signing_secret') ?: Str::random(32),
```

**Comment by driesvints** [comment]
I actually now realise that not filling in the `LEMON_SQUEEZY_SIGNING_SECRET` in the env isn't bad for local dev because that'll just cause the `VerifyWebhookSignature` signature not to be applied which shouldn't be an issue on local dev.

**Comment by DanielHudson** [comment]
Yes, and my bad rushing this PR out because it won't actually work due to the controller needing to verify the secret too...

File: src/Console/ListenCommand.php (hunk 1 above)
Comment (DanielHudson) [reply src/Console/ListenCommand.php:269]: https://github.com/lmsqueezy/laravel/blob/9cf73218924be59f1843e2e8c66434b0eba13c69/src/Http/Controllers/WebhookController.php#L41-L42

It wouldn't actually work since the incoming `LEMON_SQUEEZY_SIGNING_SECRET` won't match what is being looked for in the `VerifyWebhookSignature` middleware.

I tend to agree that perhaps this is not even really an issue, maybe just document that if using the listen command then ensure that a "dummy" `LEMON_SQUEEZY_SIGNING_SECRET` is be given?

**Comment by driesvints** [comment]
I tested the changes I made and verified the secret was the same in the Lemon Squeezy dashboard as the one that was generated. 

Thanks for the PR! Will release this.

**Comment by DanielHudson** [comment]
Hah - totally overlooked that the signing secret isn't verified if not filled! Thanks too.
